modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
issueTrackerURL="https://github.com/ZiYueCommentary/Tianjin-Metro/issues"

[[mods]]
modId = "tjmetro"
version = "${version}"
displayName = "Tianjin Metro"
displayURL="https://modrinth.com/mod/tianjin-metro"
authors = "ZiYueCommentary"
description = "A small addon for the Minecraft Transit Railway Mod."
logoFile = "icon.png"

[[dependencies.tjmetro]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tjmetro]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.tjmetro]]
modId = "mtr"
mandatory = true
versionRange = "1.0"
ordering = "AFTER"
side = "BOTH"

[[dependencies.tjmetro]]
modId = "filters"
mandatory = true
versionRange = "1.0"
ordering = "AFTER"
side = "CLIENT"