name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        minecraft: [1.16.5, 1.17.1, 1.18.2, 1.19.2, 1.19.4, 1.20.1, 1.20.4]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Setup Forge files
        run: ./gradlew forge:setupFiles -Pminecraft_version="${{ matrix.minecraft }}"
      - name: Build with Gradle
        run: |
          NOW=$(date '+%Y-%m-%d-%H.%M')
          ./gradlew build -Pminecraft_version="${{ matrix.minecraft }}" -Partifact_date=".artifact_$NOW"
