# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Build
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        minecraft: [ 1.16.5, 1.17.1, 1.18.2, 1.19.2, 1.19.3 ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@master
      - name: Setup JDK 17
        uses: actions/setup-java@main
        with:
          java-version: 17
          distribution: 'zulu'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Setup ${{ matrix.minecraft }} ${{ matrix.loader }}
        run: ./gradlew setupLibrary -PbuildVersion="${{ matrix.minecraft }}"
      - name: Build ${{ matrix.minecraft }} ${{ matrix.loader }}
        run: ./gradlew build -PbuildVersion="${{ matrix.minecraft }}"
      - name: Capture release artifacts
        uses: actions/upload-artifact@main
        with:
          name: Artifacts
          path: build/release
      - name: Upload files to SFTP
        env:
          MY_KEY: ${{ secrets.FTP_HOST }}
        if: ${{ env.MY_KEY != '' }}
        uses: sand4rt/ftp-deployer@master
        with:
          sftp: true
          host: ${{ secrets.FTP_HOST }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote_folder: ${{ secrets.FTP_PATH }}
          local_folder: build/latest
          exclude: '["latest-lu-addon.json"]'
      - name: Upload version file to SFTP
        env:
          MY_KEY: ${{ secrets.FTP_HOST }}
        if: ${{ env.MY_KEY != '' && matrix.minecraft == '1.16.5' }}
        uses: sand4rt/ftp-deployer@master
        with:
          sftp: true
          host: ${{ secrets.FTP_HOST }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remote_folder: ${{ secrets.FTP_PATH }}
          local_folder: build/latest
          include: '["latest-lu-addon.json"]'
